FROM local/f5gc:ubt18 AS builder
MAINTAINER YOSHIFUMI sumida <yoshifumi.sumida@gmail.com>

FROM gcr.io/distroless/base:debug
COPY --from=builder /root/go/src/free5gc/bin/ausf /opt/f5gc/bin/ausf
COPY configs /opt/f5gc/etc/
ENV PATH ${PATH}:/opt/f5gc/bin

ENTRYPOINT ["ausf", "--ausfcfg", "/opt/f5gc/etc/ausfcfg.conf"]
